/*
 * Minimal runtime for bootstrap Stage0-produced executables.
 *
 * Stage0 currently emits an entrypoint called `weave_main` with signature:
 *   int weave_main(void)
 *
 * This runtime provides the process `main` and forwards to `weave_main`.
 */

#include <stdio.h>

/* Generated by the compiler. */
extern int weave_main(void);

int main(void) {
    return weave_main();
}

